# Generated by Django 3.0 on 2020-01-06 16:58

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=blog.models.rename_file, verbose_name='Прикрепленный файл')),
                ('file_create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания статьи')),
                ('article_published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации статьи')),
                ('article_image', models.ImageField(upload_to=blog.models.rename_image, verbose_name='Картинка статьи')),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('article_files', models.ManyToManyField(to='blog.UploadedFile', verbose_name='Прикрепленный файлы к статье')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
