# Generated by Django 3.0 on 2020-01-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200107_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text_short',
            field=models.TextField(default='', verbose_name='Краткое содержание'),
            preserve_default=False,
        ),
    ]
