# Generated by Django 3.0 on 2020-01-12 07:07

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_article_text_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_files',
            field=models.ManyToManyField(blank=True, null=True, to='blog.UploadedFile', verbose_name='Прикрепленный файлы'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.rename_image, verbose_name='Изображение'),
        ),
    ]
