# Generated by Django 3.0 on 2020-01-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200112_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletype',
            old_name='article_type',
            new_name='type',
        ),
    ]
