# Generated by Django 3.0 on 2020-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200115_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_views',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колличество просмотров'),
        ),
    ]
