# Generated by Django 3.0 on 2020-01-24 09:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200124_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.rename_image, verbose_name='Изображение')),
                ('files', models.ManyToManyField(blank=True, to='blog.UploadedFile', verbose_name='Прикрепленный файлы')),
            ],
        ),
    ]
