# Generated by Django 3.0 on 2020-01-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('sender', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('massage', models.TextField(verbose_name='Сообщение')),
                ('copy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Обратная связь',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакт'},
        ),
    ]
