# Generated by Django 3.0 on 2020-01-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200129_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='article_image',
            new_name='news_image',
        ),
    ]
